---

- name: "Launch Windows AMI"
  hosts: localhost
  gather_facts: no
  vars:
    local_account_username: "administrator"
    local_account_password: "Emergent-42-foo!"
    
  roles:
  - launch_windows_ami

  tasks:
  - name: "Wait for connection on all hosts."
    wait_for:
      host: "{{ item['tagged_instances'][0]['private_ip'] }}"
      port: 5986
      timeout: 300
    loop: "{{ ec2.results }}"
    loop_control:
      label: "{{ item['tagged_instances'][0]['private_ip'] }}"