---

- name: "Launch Windows AMI"
  hosts: localhost
  gather_facts: no
  vars:
    local_account_username: "administrator"
    local_account_password: "Emergent-42-foo!"
    
  tasks:
  - name: "Create user data"
    set_fact:
      user_data: "{{ lookup('template', 'userdata.txt.j2') }}"

  - name: "Launch AMI"
    include_role:
      name: launch_ami

  - name: "Wait for connection on all hosts."
    wait_for:
      host: "{{ item['tagged_instances'][0]['private_ip'] }}"
      port: 5986
      timeout: 300
    loop: "{{ ec2.results }}"
    loop_control:
      label: "{{ item['tagged_instances'][0]['private_ip'] }}"