---
- name: Check for Windows Updates
  win_updates:
    category_names: "{{ categories | default(omit) }}"
    state: searched
  register: update_search_results

- name: Show results
  debug:
    var: update_search_results

- name: Install Windows Updates
  win_updates:
    category_names: "{{ categories | default(omit) }}"
    state: installed
    log_path: c:\ansible_win_updates.txt
    reboot: "{{ reboot_server }}"
  register: update_result

# - name: Reboot if required
#   win_reboot:
#   when: update_result.reboot_required
